apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "atp3-playwright-runner.fullname" . }}
  labels:
    app: {{ include "atp3-playwright-runner.name" . }}
    metrics-type: atp3-service
spec:
  ttlSecondsAfterFinished: {{ .Values.ATP_RUNNER_JOB_TTL }}
  template:
    metadata:
      labels:
        metrics-type: atp3-service
    spec:
      {{- if .Values.SECURITY_CONTEXT_ENABLED }}
      securityContext:
        {{- include "securityContext.pod" . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: atp3-playwright-runner
        image: '{{ default .Values.DOCKER_TAG .Values.ATP_TESTS_DOCKER_TAG }}'
        {{- if .Values.SECURITY_CONTEXT_ENABLED }}
        securityContext:
          {{- include "securityContext.container" . | nindent 12 }}
        {{- end }}
        resources:
          requests:
            memory: '{{ .Values.MEMORY_REQUEST | default "1000Mi" }}'
            cpu: '{{ .Values.CPU_REQUEST | default "100m" }}'
          limits:
            memory: '{{ .Values.MEMORY_LIMIT | default "2000Mi" }}'
            cpu: '{{ .Values.CPU_LIMIT | default "500m" }}'
        env:
          - name: ATP_TESTS_GIT_REPO_URL
            value: "{{ .Values.ATP_TESTS_GIT_REPO_URL }}"
          - name: ATP_TESTS_GIT_REPO_BRANCH
            value: "{{ .Values.ATP_TESTS_GIT_REPO_BRANCH }}"
          - name: ENVIRONMENT_NAME
            value: "{{ .Values.ENVIRONMENT_NAME }}"
          - name: ENV_CONFIGURATION_TEMPLATE_FILENAME
            value: {{ .Values.ENV_CONFIGURATION_TEMPLATE_FILENAME | default "environment-configuration-template.json" | quote }}
          - name: ATP_STORAGE_PROVIDER
            value: "{{ .Values.ATP_STORAGE_PROVIDER }}"
          - name: ATP_STORAGE_REGION
            value: "{{ .Values.ATP_STORAGE_REGION }}"
          - name: ATP_STORAGE_SERVER_URL
            value: "{{ .Values.ATP_STORAGE_SERVER_URL }}"
          - name: ATP_STORAGE_SERVER_UI_URL
            value: "{{ .Values.ATP_STORAGE_SERVER_UI_URL }}"
          - name: ATP_REPORT_VIEW_UI_URL
            value: "{{ .Values.ATP_REPORT_VIEW_UI_URL }}"
          - name: ATP_RUNNER_JOB_EXIT_STRATEGY
            value: "{{ .Values.ATP_RUNNER_JOB_EXIT_STRATEGY }}"
          - name: CURRENT_DATE
            value: "{{ .Values.CURRENT_DATE }}"
          - name: CURRENT_TIME
            value: "{{ .Values.CURRENT_TIME }}"
          - name: ATP_STORAGE_BUCKET
            value: "{{ .Values.ATP_STORAGE_BUCKET }}"
          - name: ENABLE_JIRA_INTEGRATION
            value: "{{ .Values.ENABLE_JIRA_INTEGRATION }}"
          - name: ATP_MONITORING_ENABLED
            value: "{{ .Values.ATP_MONITORING_ENABLED }}"
          - name: ATP_METRICS_ENABLED
            value: "{{ .Values.ATP_METRICS_ENABLED }}"
          - name: ATP_METRICS_URL
            value: "{{ .Values.ATP_METRICS_URL }}"
          - name: ATP_METRICS_TYPE
            value: "{{ .Values.ATP_METRICS_TYPE }}"
          - name: ATP_METRICS_AUTH_TYPE
            value: "{{ .Values.ATP_METRICS_AUTH_TYPE }}"
          - name: DEBUG_MODE
            value: "{{ .Values.DEBUG_MODE }}"
          - name: PLAYWRIGHT_TRACE_MODE
            value: "{{ .Values.PLAYWRIGHT_TRACE_MODE }}"
          - name: TEST_PARAMS
            value: {{ toJson .Values.TEST_PARAMS | quote }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "{{ .Values.OTEL_EXPORTER_OTLP_ENDPOINT }}"
          - name: OTEL_SERVICE_NAME
            value: "{{ .Values.OTEL_SERVICE_NAME }}"
          - name: ATP_PROJECT_ID
            value: "{{ .Values.ATP_PROJECT_ID }}"
          - name: ATP_ENVGENE_CONFIGURATION
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpEnvgeneConfiguration
          - name: ATP_TESTS_GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpTestsGitToken
          - name: ATP_STORAGE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpStorageUsername
          - name: ATP_STORAGE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpStoragePassword
          - name: DEFAULT_TENANT_ADMIN_LOGIN
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: defaultTenantAdminLogin
          - name: DEFAULT_TENANT_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: defaultTenantAdminPassword
          - name: DEFAULT_TENANT_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: defaultTenantName
          - name: CONSUL_ADMIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: consulAdminToken
          - name: ATP_METRICS_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpMetricsUser
          - name: ATP_METRICS_PASS
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpMetricsPass
          - name: ATP_METRICS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "atp3-playwright-runner.fullname" . }}-secret
                key: atpMetricsToken
        envFrom:
          - configMapRef:
              name: {{ include "atp3-playwright-runner.fullname" . }}-cm
          - configMapRef:
              name: {{ include "atp3-playwright-runner.fullname" . }}-extra
              optional: true
      restartPolicy: Never
  backoffLimit: 0
