'use strict';

const { NodeSDK } = require('@opentelemetry/sdk-node');
const { HttpInstrumentation } = require('@opentelemetry/instrumentation-http');
const { UndiciInstrumentation } = require('@opentelemetry/instrumentation-undici');
const { OTLPTraceExporter } = require('@opentelemetry/exporter-trace-otlp-http');
const { B3Propagator, B3InjectEncoding } = require('@opentelemetry/propagator-b3');
const { W3CTraceContextPropagator, CompositePropagator } = require('@opentelemetry/core');
const { AsyncLocalStorageContextManager } = require('@opentelemetry/context-async-hooks');
const { propagation, ROOT_CONTEXT } = require('@opentelemetry/api');

const traceparent = process.env.TRACEPARENT;
if (!traceparent) {
  // No trace context from trace-init.sh -- skip OTel bootstrap entirely
  return;
}

// Extract TRACEPARENT into an OTel context so downstream spans share the
// trace-id generated by trace-init.sh rather than starting a new trace.
const extractedCtx = propagation.extract(ROOT_CONTEXT, { traceparent });

// AsyncLocalStorage returns ROOT_CONTEXT when no explicit context is active.
// Override active() so that case falls back to extractedCtx, which carries
// the bash-generated trace-id.  Any explicitly-started span still wins.
class InheritedContextManager extends AsyncLocalStorageContextManager {
  active() {
    const ctx = super.active();
    return ctx === ROOT_CONTEXT ? extractedCtx : ctx;
  }
}

const sdk = new NodeSDK({
  serviceName: process.env.OTEL_SERVICE_NAME || 'atp3-playwright-runner',
  traceExporter: process.env.OTEL_EXPORTER_OTLP_ENDPOINT
    ? new OTLPTraceExporter()
    : undefined,
  instrumentations: [
    new HttpInstrumentation(),
    new UndiciInstrumentation(),
  ],
  textMapPropagator: new CompositePropagator({
    propagators: [
      new W3CTraceContextPropagator(),
      new B3Propagator({ injectEncoding: B3InjectEncoding.MULTI_HEADER }),
    ],
  }),
  contextManager: new InheritedContextManager().enable(),
});

sdk.start();
