name: Build and Publish Release Docker Image
run-name: "Dev build repository: ${{ github.ref_name }} #${{ github.run_number }}"

on:
  push:
    branches-ignore:
      - "**release*"
      - "prettier/**"
      - "dependabot/**"
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/**"
  workflow_dispatch: { }
  pull_request:
    branches: [ main ]
    types:
      [ opened, reopened, synchronize ]

env:
  VERSION_TYPE: patch

permissions:
  contents: write
  packages: write

jobs:
  docker-build:
    name: "Build and Publish Docker Image"
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
      tags: "${{ steps.prepare_tags.outputs.new_tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: "Prepare tags"
        id: prepare_tags
        run: |
          echo "Check current tag"
          git fetch --tags
          TAG=$(git tag --list 'v*' --sort=-v:refname | tr -d '\r' | head -n 1)
          TAG=${TAG#v}
          echo "Current tag: $TAG"

          if [[ -z "$TAG" ]]; then
            NEW_TAG="1.0.0"
          else
            MAJOR=$(echo "$TAG" | cut -d. -f1)
            MINOR=$(echo "$TAG" | cut -d. -f2)
            PATCH=$(echo "$TAG" | cut -d. -f3)
            if [ "$VERSION_TYPE" == "major" ]; then
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
            elif [ "$VERSION_TYPE" == "minor" ]; then
              MINOR=$((MINOR + 1))
              PATCH=0
            else
              PATCH=$((PATCH + 1))
            fi
            NEW_TAG="$MAJOR.$MINOR.$PATCH"
          fi

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "New version will be: $NEW_TAG"

      - name: "Summary step"
        run: |
          echo "**Tags:** ${{ steps.prepare_tags.outputs.new_tag }}" >> $GITHUB_STEP_SUMMARY

  helm-chart-release:
    needs: [ build-and-push ]
    if: ${{ needs.build-and-push.result == 'success' }}
    uses: netcracker/.github/workflow-templates/helm-charts-release.yaml@main
    with:
      release: ${{ needs.docker-build.outputs.tags }}
